@Library( 'essLib')_

//
// Context
//
String gitUrl
String gitBranch
String buildBranch
String buildTag
String project
String artifact
String version
Map    cloneInfo
List   culprits = []
String commit

//
// Pipeline
//
pipeline {

    agent any

    environment {
        GIT_BRANCH = 'poc/INTYGFV-15255'
        GIT_CREDENTIALS = 'intyg-github'
    }

    stages {

        stage('Setup') {
            steps {
                script {

                    // Setup environment
                    gitUrl      = essJob.getProperty( name:'git.url', value:essJob.getScmUrl())
                    gitBranch   = essJob.getProperty( name:'git.branch', value:'master')
                    buildBranch = gitBranch
                    buildTag    = ''

                    cloneInfo = essGit.clone url: gitUrl, branch: buildBranch

                    buildTag = essJob.getProperty( name:'artifact.version')

                    essJob.tagBuildName tag: buildTag

                    commit   = essGit.getCommit()
                    project  = essJob.getProperty( name:'project.name')
                    artifact = essJob.getProperty( name:'artifact.name')
                    version  = essCmn.getVersion()
                    culprits = essGit.getCulpritsMail( info:cloneInfo)
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    essDocker.build( project:project, name:artifact, version:version, commit:commit, url:gitUrl, tag:buildTag, path:'./bks/app-builder-image/')
                }
            }
        }

        stage('Notify') {
            steps {
                script {
                    essNotify.success()
                }
            }
        }
    }
}
