#!/bin/bash

declare -A APPS

APPS=(
  ["cs"]=certificate-service
  ["ia"]=intygsadmin
  ["it"]=intygstjanst
  ["ls"]=logsender
  ["mi"]=minaintyg
  ["pp"]=privatlakarportal
  ["rs"]=rehabstod
  ["st"]=statistik
  ["wc"]=webcert
  ["cas"]=certificate-analytics-service
  ["cps"]=certificate-print-service
  ["cts"]=customer-terminate-service
  ["ips"]=intyg-proxy-service
  ["pps"]=private-practitioner-service
  ["srs"]=srs
  ["sjut"]=sjut
  ["wc-frontend"]=webcert-frontend
  ["rs-frontend"]=rehabstod-frontend
  ["mi-frontend"]=mianintyg-frontend
)

args=$@
echo "Stopping containers ${args[@]}"

for APP in ${args[@]}; do
  app="${APPS[${APP}]}"
  docker compose stop "$app"
done

