-- This script deletes certificates and related information for a certain patient.


DELIMITER $$
CREATE PROCEDURE delete_certificates()
BEGIN

    DECLARE caughtException int DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET caughtException = 1;


    START TRANSACTION;


    SET @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER := '19121212-1212';
    SET @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER_WITHOUT_DASH := REPLACE(@DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER, '-', '');
    SELECT CONCAT('Delete certificates for ', @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER, ' and ', @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER_WITHOUT_DASH, '.');


    -- Create temporary tables
    CREATE TEMPORARY TABLE `TEMP_CERTIFICATES_TO_DELETE` (
        `ID` varchar(64) NOT NULL,
        PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TEMPORARY TABLE `TEMP_ARENDE_TO_DELETE` (
        `ID` bigint(20) NOT NULL,
        PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TEMPORARY TABLE `TEMP_HANDELSE_TO_DELETE` (
         `ID` bigint(20) NOT NULL,
         PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TEMPORARY TABLE `TEMP_FRAGASVAR_TO_DELETE` (
       `ID` bigint(20) NOT NULL,
       PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


    -- Fill temporary tables
    INSERT INTO TEMP_CERTIFICATES_TO_DELETE SELECT INTYGS_ID FROM INTYG WHERE PATIENT_PERSONNUMMER = @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER;
    INSERT INTO TEMP_ARENDE_TO_DELETE SELECT ID FROM ARENDE WHERE PATIENT_PERSON_ID IN (@DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER, @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER_WITHOUT_DASH);
    INSERT INTO TEMP_HANDELSE_TO_DELETE SELECT ID FROM HANDELSE WHERE PATIENT_PERSON_ID IN (@DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER, @DELETE_CERTIFICATES_FOR_PATIENT_PERSONAL_NUMBER_WITHOUT_DASH);
    INSERT INTO TEMP_FRAGASVAR_TO_DELETE SELECT internReferens FROM FRAGASVAR WHERE INTYGS_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);


    -- Delete from relevant tables from temporary tables
    DELETE FROM PAGAENDE_SIGNERING WHERE INTYG_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);
    DELETE FROM SIGNATUR WHERE INTYG_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);

    DELETE FROM MEDICINSKT_ARENDE WHERE ARENDE_ID IN (SELECT ID FROM TEMP_ARENDE_TO_DELETE);
    DELETE FROM ARENDE_KONTAKT_INFO WHERE ARENDE_ID IN (SELECT ID FROM TEMP_ARENDE_TO_DELETE);
    DELETE FROM ARENDE_UTKAST WHERE INTYGS_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);
    DELETE FROM ARENDE WHERE ID IN (SELECT ID FROM TEMP_ARENDE_TO_DELETE);

    DELETE FROM CERTIFICATE_EVENT WHERE CERTIFICATE_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);
    DELETE FROM CERTIFICATE_EVENT_FAILED_LOAD WHERE CERTIFICATE_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);
    DELETE FROM CERTIFICATE_EVENT_PROCESSED WHERE CERTIFICATE_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);

    DELETE FROM EXTERNA_KONTAKTER WHERE FRAGASVAR_ID IN (SELECT ID FROM TEMP_FRAGASVAR_TO_DELETE);
    DELETE FROM KOMPLETTERING WHERE FRAGASVAR_ID IN (SELECT ID FROM TEMP_FRAGASVAR_TO_DELETE);
    DELETE FROM FRAGASVAR WHERE INTYGS_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);

    DELETE FROM NOTIFICATION_REDELIVERY WHERE HANDELSE_ID IN (SELECT ID FROM TEMP_HANDELSE_TO_DELETE);
    DELETE FROM HANDELSE_METADATA WHERE HANDELSE_ID IN (SELECT ID FROM TEMP_HANDELSE_TO_DELETE);
    DELETE FROM HANDELSE WHERE ID IN (SELECT ID FROM TEMP_HANDELSE_TO_DELETE);

    DELETE FROM REFERENS WHERE INTYG_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);

    DELETE FROM INTYG WHERE INTYGS_ID IN (SELECT ID FROM TEMP_CERTIFICATES_TO_DELETE);


    -- Drop temporary tables
    DROP TABLE TEMP_CERTIFICATES_TO_DELETE;
    DROP TABLE TEMP_ARENDE_TO_DELETE;
    DROP TABLE TEMP_HANDELSE_TO_DELETE;
    DROP TABLE TEMP_FRAGASVAR_TO_DELETE;


    IF (caughtException) THEN
        ROLLBACK;
        SELECT 'Transaction rolled back due to sql exception. No changes were introduced.';
    ELSE
        COMMIT;
        SELECT 'Deletion of certificates was successfully.';
    END IF;


END $$
DELIMITER ;


USE webcert;
CALL delete_certificates;
DROP PROCEDURE delete_certificates;
