apiVersion: v1
kind: Template
metadata:
  name: artifactupload-pod
parameters:
- name: APP_NAME
  required: true
- name: SOURCE_PATH
  required: true
- name: BUILD_VERSION
  required: true
- name: CALLBACK_URL
  required: true
- name: BUILD_TAG
  required: true
- name: IMAGE
  required: true
- name: NO_PROXY
  required: true
  value: "*"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${BUILD_TAG}"
    labels:
      app: ${APP_NAME}
  spec:
    containers:
      - env:
        - name: SOURCE_PATH
          value: ${SOURCE_PATH}
        - name: CALLBACK_URL
          value: ${CALLBACK_URL}
        - name: NO_PROXY
          value: ${NO_PROXY}
        - name: no_proxy
          value: ${NO_PROXY}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
        image: ${IMAGE}
        imagePullPolicy: Always
        name: ${BUILD_TAG}
        command: [ "curl -v -u ind-ocpt1:7cCqk55oKv --upload-file /tmp/src/tools/liquibase-runner/build/distributions/privatlakarportal-liquibase-runner-1.14.0.13.tar https://nexus.drift.inera.se/repository/maven-releases/se/inera/privatlakarportal/privatlakarportal-liquibase-runner/1.14.0.13/privatlakarportal-liquibase-runner-1.14.0.13.tar" ]
    restartPolicy: Never

