kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-bootapp-binary
parameters:
  - name: APP_NAME
    required: true
  - name: IS_APP_NAME
    required: true
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: STAGE
    required: true
    value: "test"
  - name: COMMON_VERSION
    value: "NA"
  - name: INFRA_VERSION
    value: "NA"
  - name: REF_DATA_VERSION
    value: "NA"
  - name: BUILD_VERSION
    required: true
    value: 1.0-OPENSHIFT
  - name: GRADLE_USER_HOME
    value: "/tmp/src/.gradle"
    required: true
  - name: E_UID
    value: "1000310000"
    required: true
  - name: CONTEXT_PATH
    required: true
    value: ROOT
  - name: BUILD_ARGS
    required: true
    value: "build -x Test testClasses -PuseMinifiedJavaScript -Pclient"
  - name: BUILDER_IMAGE
    required: true
    value: "s2i-war-builder-java11:11.1"
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        contextDir: /
        type: Binary
      strategy:
        sourceStrategy:
          env:
            - name: APP_NAME
              value: ${APP_NAME}
            - name: STAGE
              value: ${STAGE}
            - name: COMMON_VERSION
              value: ${COMMON_VERSION}
            - name: INFRA_VERSION
              value: ${INFRA_VERSION}
            - name: REF_DATA_VERSION
              value: ${REF_DATA_VERSION}
            - name: BUILD_VERSION
              value: ${BUILD_VERSION}
            - name: BUILDER_IMAGE
              value: ${BUILDER_IMAGE}
            - name: JAVA_TOOL_OPTIONS
              value: '-Xms512m -Xmx2048m'
            - name: BUILD_ARGS
              value: ${BUILD_ARGS}
          from:
            kind: "ImageStreamTag"
            name: ${BUILDER_IMAGE}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 600
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        dockerfile: |-
          FROM docker.drift.inera.se/intyg/springboot-base:11
          ENV APP_NAME=${APP_NAME}
          ADD ROOT.war /deployments/
        images:
          - from:
              kind: ImageStreamTag
              name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
            paths:
              - sourcePath: /tmp/artifacts/.
                destinationDir: "."
      strategy:
        type: Docker
        dockerStrategy:
          pullSecret:
            name: "nexus-registry"
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-verified
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
